- id: train_mixmatch
  root: cifar10
  num_epochs: 100
  batch_size: 128
  learning_rate: 0.0001
  val_ratio: 0.1
  unlabel_ratio: 0.9
  num_class: 10
  label_batch_size: 64
  rampup_length: 100
  mt_alpha: 0.999
  mm_alpha: 0.75
  T: 0.5
  
